### ISSUE TITLE
Finalise user manual

### ISSUE THREAD

**Issue by jarmarshall** [DiODeProject/MuMoT#139]
User manual to be finalised - in particular keyword arguments (section 9) need to be fully populated / updated, with defaults included (in the form `<keyword> = <default>: <description>` (**N.B.** it would be good to check docstrings implement this format at the same time)

**Comment by jarmarshall** [comment]
PS all please make sure not to refer to section numbers; these can change, confusing the reader; instead, refer to the section title in the link text...

**Comment by tbose1** [comment]
Added sections 9.4 (table of getter functions) and 10.4 (small section about stoichiometry functions) via 1bfa1427af9aae2f6b7f9b67d4b851ea8c865150. If I remember correctly I removed the keyword arguments for plotting on purpose some time ago because not every plotting keyword is available in every plotting function (please see also my previous comment above). However, all plot formatting keywords specific to each plotting function are mentioned under heading 9.5 in the respective sections. The idea is that a user decides which plotting function to use and then checks the user manual which options are available. Otherwise (in case of a general plot keyword section) we would list all plotting keywords but then would also need to mention for each keyword for which plotting function this is available. I would prefer the way it's currently implemented.

**Comment by jarmarshall** [comment]
@joefresna - new sections to edit / add:

- []  keywords for field views
- [] section under 'Advanced users' on setting noise calculation parameters in field views via keywords / widgets

**Comment by jarmarshall** [comment]
Also need to add advanced sections for accessing raw mathematical objects (issue #211) and simulation data (issue #288)

- [ ] access math objects
- [ ] access simulation data

**Comment by jarmarshall** [comment]
Also, provide instructions on downloading results (see pull request #303)
