### ISSUE TITLE
Check multi-controller functionality for all views

### ISSUE THREAD

**Issue by tbose1** [DiODeProject/MuMoT#148]
Multi-controllers seem to have problems with the advanced options widgets. For example,
when copied & pasted from multi-controller bookmarks then executing the multi-controller command causes a key error for arguments from advanced options controllers.

See also section 11 in the test suite where I commented out the cells that cause problems.

**Comment by jarmarshall** [comment]
Update: I think I've narrowed this down to a conflict between the `params` keyword and setting advanced options _via keywords_. If advanced option keywords are used, then `params` _must_ be defined on creation of the view. If advanced option keywords are not used, for example because `initWidgets` is used to do the same job, then `params` can be defined on creation of the view, or at the multi controller level.

**Comment by jarmarshall** [comment]
This will be fixed in pull request #234 - specific changes are the addition of two new functions:
* `_getWidgetParamValue()`
* `_getInitialState()`

These should be used in any definition of `_update_view_specific_params()` and probably some other places as well which will only become apparent through future use, since exhaustive testing of multicontroller functionality is inherently impractical.
