### ISSUE TITLE
Consider appropriate unstable fixed point designation for Lotka-Volterra and Brusellator equations

### ISSUE THREAD

**Issue by jarmarshall** [DiODeProject/MuMoT#257]
The Lotka-Volterra field plot shows a blue unstable fixed point at the centre of the cycles, whereas for the Brusellator this is red. The reason for the difference is not clear; consider plotting in the same colour, or not plotting one or both?

**Comment by tbose1** [comment]
Solved with commit dc654b8a220fb75763396ebd3357f144431b2e5f. Fixed points with purely imaginary eigenvalues (such as in the Lotka-Volterra model) are not drawn anymore.

**Comment by jarmarshall** [comment]
@tbose1 in the user manual and paper we need to clarify what the hollow red circle denotes as observed in, for example, the oscillatory regime of the Brusellator - can you explain here please? Thanks

**Comment by tbose1** [comment]
The colours of the special points in the field-plots are:

**2D systems:**
red hollow circle = unstable fixed point (real parts of all eigenvalues larger than zero)
green full circle = stable fixed point (real parts of all eigenvalues smaller than zero)
blue hollow circle = saddle point (one real part of the two eigenvalues larger than zero, and the one smaller than zero)

**3D systems:**
red hollow circle = unstable fixed point (at least one real part of one of the 3 eigenvalues eigenvalue is larger than zero)
green full circle = stable fixed point (real parts of all eigenvalues smaller than zero)

The distinction between 2D and 3D systems is because of the clear definition of a saddle point in 2D, whereas in 3D I'm not certain if a saddle point exists as such or can be identified by simply checking the eigenvalues. @jarmarshall please let me know if we only want to have two colours in 2D (like in 3D), i.e. red (or blue) hollow circle and full green circle.

**Comment by jarmarshall** [comment]
Perfect, that makes sense thanks - for 3d I am not sure either - I think a saddle in 3D can exist but I am not sure if the eigenvalues are sufficient to test for that.
