### ISSUE TITLE
Improve test suite to avoid unnecessary error messages

### ISSUE THREAD

**Issue by tbose1** [DiODeProject/MuMoT#262]
After making several attempts to complete local testing successfully using tox I found several cells in a couple of notebooks that lead to error messages, presumably because the execution of some cells time out (those are commands that work fine when the notebook is run manually). In particular I noticed that some (not all) cells making use of `SSA` lead to such error messages in the automated testing. For now, I commented out the cells that caused problem in my local tests in MuMoTtest_MultiController.ipynb, MuMoTtest_NoiseFixedPoints.ipynb and MuMoTtest.ipynb. I will upload the revised notebooks shortly. Although this is something I observed in relation with local testing we should consider it also relevant for remote testing, as the same test-framework is being used.

In general, I think we should think about a more suitable test suite in the long term where cells that can be executed successfully do not lead to error messages in the automated testing. In particular we should generate shorter meaningful test notebooks with code that can be executed quickly. Otherwise working on resolving errors can take up a huge amount of time.

**Comment by jarmarshall** [comment]
This has been an ongoing issue (e.g. see issue #235) and we’ve managed so far... rather than reduce coverage as a short term solution I would rather re-run Travis jobs as needed... on finishing the first release we should re-enable these tests. Some work to improve the robustness of CI early in second release development will be good; there has been some discussion of the monolith test notebook but I don’t think it’s size was identified as the problem.

**Comment by tbose1** [comment]
Re-running the tests locally a couple of times by calling tox always produced the same error message which might not occur with tests on travis-ci.org. Re-enabling the tests is easily done but if I enable the cells again which I commented out I won't be able to make use of the testing functionality in my local MuMoT copy, as this will fail. I agree it's not the size of the notebook but the outputs of particular cells which are difficult to deal with.

**Comment by willfurnass** [comment]
For commands that don't produce output for >10 mins Travis can be told to wait longer by prefixing commands with `travis_wait` ([more info here](https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received)).  However, that may not be the problem here; we might have encountered issues where the test suite hangs due to a lack of Javascript and/or human interaction.

**Comment by willfurnass** [comment]
@tbose1 What are the error/warning messages you mention in https://github.com/DiODeProject/MuMoT/issues/262#issue-409207123?

**Comment by tbose1** [comment]
Please see the file attached. I successively tested the cells that failed by calling tox and copied and pasted what was returned (the vertical dots indicate that I omitted some output which I thought is not so useful regarding the problem). As you can see, the problem is that calculations time out for some reason. These error messages are repeatable.

[issuesTesting.txt](https://github.com/DiODeProject/MuMoT/files/2861173/issuesTesting.txt)

**Comment by willfurnass** [comment]
@tbose1 Apologies for not replying much sooner.  I suspect what is needed here is to pass  `--nbval-cell-timeout=Xs` to `pytest` in `tox.ini`, where `X` is an integer greater than 5.

**Comment by willfurnass** [comment]
Is this happening?

**Comment by jarmarshall** [comment]
@willfurnass - @tbose1 has left the project now and returned to Germany - please could you try to get this working? Thanks
