### ISSUE TITLE
Bookmark button generates a text without the list of rates 

### ISSUE THREAD

**Issue by joefresna** [DiODeProject/MuMoT#277]
The list of so-called _free parameters_ is not printed out with the bookmark functionality

**Comment by jarmarshall** [comment]
Sorry, I don't really understand - bookmarks have been working for a while... can you be more specific?

**Comment by joefresna** [comment]
when I click on "Bookmark" and I run the command `ctrl.showLogs()`, I get this types of text:

`bookmark = <modelName>.multiagent(initialState = {'B': 0.1, 'U': 0.7, '\\alpha': 0.2}, maxTime = 3.0, timestepSize = 0.0714285714285714, randomSeed = 1146043001, netType = 'full', visualisationType = 'evo', plotProportions = False, realtimePlot = False, runs = 1, aggregateResults = True, silent = False, bookmark = False)`

which misses the `param` part.

**Comment by joefresna** [comment]
I put here an `integrate()` example to remove any blame from `MuMoTstochasticSimulationController` 
:-) 

bookmark = <modelName>.integrate(showStateVars=['B', '\\alpha'], initialState = {'B': 1.0, 'U': 0.0, '\\alpha': 0.0}, maxTime = 3.0, plotProportions = False, conserved = True, bookmark = False)

**Comment by joefresna** [comment]
as I am currently fixing the code, I can look into this

**Comment by jarmarshall** [comment]
Argh! I'm sure this was working in pull request #234 a couple of months ago... have to work out what happened since then... thanks

**Comment by joefresna** [comment]
I found the issue, but I am sorry, the issue was already there at #234 
Although, I noticed new problems too.... #279

**Comment by jarmarshall** [comment]
This is really odd, since I tested bookmark generation and execution by hand in the notebook `MuMoTtest_MultiController` in pull request #234. This makes me worry... I'm also surprised by issue #285 for the same reason, although need to look at that in a bit more detail. Are you sure you pulled the latest version of master before starting work? 😉 : Semi-serious actually as if there's been some code-contamination through a version control failure then other recent changes may have been undone. I will have to review your commit to see where the bug was then try and figure out what's happened, it seems... 😞

**Comment by joefresna** [comment]
Because #286 makes many many changes, I also was worried to have introduced the bug myself. Especially, issue #285 looks annoying... 
So I did the test to revert back to commit https://github.com/DiODeProject/MuMoT/commit/72887ad3cc6d22d53c82ce032dc5a864cd7d2c29 and these bugs are still there.
:-(  sorry...

**Comment by jarmarshall** [comment]
OK - I rolled back to 9f77564b2e95ad5b6760eb69964987732d877045 and I believe this issue may have been there all along because issue #255 was there at the time undetected - the history of that error is hard to establish as git blame doesn't seem to account for the fact the line moves around.. when pull request #286 is merged (pending fixes from @joefresna) I would like to look at bookmark logic again, as trying to bookmark all multicontrollers in `TestNotebooks/MiscTests/MuMoTtest_MultiController` should test the code to destruction...
